version: '3.8'
services:
  n8n:
    build: .
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=thomass
      - N8N_BASIC_AUTH_PASSWORD=275227
      - N8N_ENCRYPTION_KEY=clave_secreta_32_caracteres
    restart: always
