version: '3.8'
services:
  n8n:
    build: .
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=tu_usuario  # ¡Cambia esto!
      - N8N_BASIC_AUTH_PASSWORD=tu_contraseña  # ¡Cambia esto!
      - N8N_ENCRYPTION_KEY=clave_secreta_32_caracteres  # ¡Obligatorio!
    restart: always
