version: '3.8'
services:
  n8n:
    build: .
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=thomas
      - N8N_BASIC_AUTH_PASSWORD=275227
      - N8N_ENCRYPTION_KEY=l="W`kQ!hU]BPHoB41qtR:@S<krDbs%Lam$QWcc1X)2JzaYl,>L=p(3QxZvzR<N%"
    restart: always
